@dotnet_resource_HostAddress = http://localhost:8080

POST {{oauthUrl}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type = password &
client_id = {{clientId}} &
username = {{clientUsername}} &
password = {{clientSecret}}
> {%
    client.global.set("access_token", response.body.access_token)
%}

###
GET {{dotnet_resource_HostAddress}}/api/weatherforecast
Authorization: Bearer {{access_token}}

###
GET {{dotnet_resource_HostAddress}}/api/treenode
Authorization: Bearer {{access_token}}

###
GET {{dotnet_resource_HostAddress}}/api/treenode/1
Authorization: Bearer {{access_token}}

###
POST {{dotnet_resource_HostAddress}}/api/treenode
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "name": "node-1",
  "description": "Node 1"
}

###
DELETE {{dotnet_resource_HostAddress}}/api/treenode/3
Authorization: Bearer {{access_token}}

###
